 name: Publish Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install docapella
        run: cargo install --git https://github.com/Doctave/docapella.git docapella

      - name: Build docs
        run: docapella build

#      - name: Create tar.gz archive
#        run: tar -czf docs.tar.gz _build

#      - name: Upload tar.gz artifact
#        uses: actions/upload-artifact@v4
#        with:
#          path: docs.tar.gz

      - name: Upload static files as artifact
        uses: actions/upload-artifact@v4
        with:
          path: _build


# Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
