name: Rebuild Algolia index
on:
  workflow_dispatch:
jobs:
  update-algolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set environment variables from action inputs
        shell: bash
        run: |
          echo "MODE=reindexation" >> $GITHUB_ENV
          echo "ALGOLIA_INDEX=${{ secrets.ALGOLIA_INDEX }}" >> $GITHUB_ENV
          echo "ALGOLIA_APPLICATION_ID=${{ secrets.ALGOLIA_APPLICATION_ID }}" >> $GITHUB_ENV
          echo "ALGOLIA_API_KEY=${{ secrets.ALGOLIA_API_KEY }}" >> $GITHUB_ENV

      - name: Rebuild Algolia index
        shell: bash
        run: node .github/actions/update-algolia/dist/index.js
