# Fake test that always passes (for now), because the generator requires a test job in each of its targets
name: Run unit tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: exit 0